version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - backend_data:/app/instance
    environment:
      - FLASK_ENV=production
    networks:
      - webcursos_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - webcursos_network

volumes:
  backend_data:

networks:
  webcursos_network:
    driver: bridge